service: s3UploadToDB
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
functions:
  function1:
    handler: index.handler
    events:
      - s3:
          bucket: upload-s3-file-to-dynamo
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
