service: s3UploadToDB
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  environment:
    TableName: ${self:custom.TableName}

custom:
  BucketName: upload-s3-file-to-dynamo
  TableName: carOwnerTable

layers:
  nodemodules:
    package:
      artifact: layers/nodejs.zip

package:
  individually: true
  patterns:
    - "!layers/**"
    - "!node_modules/**"
    - "!package.json"
    - "!package-lock.json"

functions:
  function1:
    handler: src/index.handler
    layers:
      - !Ref NodemodulesLambdaLayer
    role: lambdaRole
    events:
      - s3:
          bucket: ${self:custom.BucketName}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

resources:
  Resources:
    lambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:TagResource
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/*:*:*"
                - Effect: "Allow"
                  Action:
                    - "s3:GetObject"
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:s3:::"
                        - ${self:custom.BucketName}
                        - "/*"
                - Effect: "Allow"
                  Action:
                    - "dynamodb:PutItem"
                  Resource: !GetAtt carOwnerTable.Arn
                - Effect: "Allow"
                  Action:
                    - "ses:SendEmail"
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:ses:"
                        - !Ref "AWS::Region"
                        - ":"
                        - ${aws:accountId}
                        - ":identity/anilaraganji123@gmail"
    carOwnerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.TableName}
        KeySchema:
          - AttributeName: customerId
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: customerId
            AttributeType: S
