service: s3UploadToDB
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}

custom:
  BucketName: upload-s3-file-to-dynamo

layers:
  nodemodules:
    package:
      artifact: layers/nodejs.zip

package:
  individually: true
  patterns:
    - "!layers/**"
    - "!node_modules/**"
    - "!package.json"
    - "!package-lock.json"

functions:
  function1:
    handler: index.handler
    layers:
      - !Ref NodemodulesLambdaLayer
    events:
      - s3:
          bucket: ${self:custom.BucketName}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
          existing: true

resources:
  Resources:
    s3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.BucketName}
    s3LambdaBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref s3Bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - "S3:*"
