service: s3UploadToDB
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    events:
      - s3:
          bucket: !Ref csvS3Bucket
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
          existing: true

resources:
  Resources:
    csvS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: s3-upload-csv-to-dynamodb
